### ISSUE TITLE
dependencies missing for installing

### ISSUE THREAD

**Issue by nerdoc** [estan/gauges#1]
I tried to setup this example - but at the setup.py step I get an error that something went wrong:

    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/twisted/test/raiser.c -o build/temp.linux-x86_64-2.7/src/twisted/test/raiser.o
    src/twisted/test/raiser.c:4:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Could it be that there is a compile dependency missing? Do you compile PyQt here? Which packages must be installed under e.g. Ubuntu to make that work?

    Command "/home/christian/demo_env/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p1xHtF/twisted/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aMfpAa-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/christian/demo_env/include/site/python2.7/twisted" failed with error code 1 in /tmp/pip-build-p1xHtF/twisted/

**Comment by estan** [comment]
This is just a guess, but I think you need to install the Python development package (`python-dev` on Ubuntu I think).

**Comment by nerdoc** [comment]
Definitely. Thanks. Maybe mention that in the README.md?

**Comment by estan** [comment]
Hm, I could mention it in the README.md, but I'm not sure that is the only build dependency. Since it's a failure during the installation of Twisted (not of the example itself), I think it's better if they document their build dependencies somewhere. Otherwise I'd have to keep track of them all :)

**Comment by nerdoc** [comment]
That's true. Another builddep is PyQt5, which on Ubuntu is somehow difficult to install within a virtualenv...
Thanks anyway.
